"""add route_path to jenis_permohonan

Revision ID: 0a499421dc22
Revises: 3b24fd54516a
Create Date: 2025-09-20 02:56:21.373179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a499421dc22'
down_revision = '3b24fd54516a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('history', schema=None) as batch_op:
        batch_op.drop_index('idx_history_permohonan')

    with op.batch_alter_table('jenis_permohonan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('route_path', sa.String(length=255), nullable=True))

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index('idx_notifications_user')

    with op.batch_alter_table('permohonan', schema=None) as batch_op:
        batch_op.drop_index('idx_permohonan_dosen')
        batch_op.drop_index('idx_permohonan_mahasiswa')
        batch_op.drop_index('idx_permohonan_status')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('idx_users_nomor_induk')
        batch_op.drop_index('idx_users_role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('idx_users_role', ['role'], unique=False)
        batch_op.create_index('idx_users_nomor_induk', ['nomor_induk'], unique=False)

    with op.batch_alter_table('permohonan', schema=None) as batch_op:
        batch_op.create_index('idx_permohonan_status', ['status_permohonan'], unique=False)
        batch_op.create_index('idx_permohonan_mahasiswa', ['id_mahasiswa'], unique=False)
        batch_op.create_index('idx_permohonan_dosen', ['id_dosen'], unique=False)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index('idx_notifications_user', ['user_id', 'is_read'], unique=False)

    with op.batch_alter_table('jenis_permohonan', schema=None) as batch_op:
        batch_op.drop_column('route_path')

    with op.batch_alter_table('history', schema=None) as batch_op:
        batch_op.create_index('idx_history_permohonan', ['permohonan_id'], unique=False)

    # ### end Alembic commands ###
