"""Initial migration

Revision ID: ba11db074a9d
Revises: 
Create Date: 2025-11-05 11:14:17.368343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba11db074a9d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fakultas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_fakultas', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jenis_permohonan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_jenis_permohonan', sa.String(length=255), nullable=False),
    sa.Column('deskripsi', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('route_path', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nomor_induk', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('nama', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'dosen', 'mahasiswa', name='user_roles'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('no_hp', sa.String(length=15), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nomor_induk')
    )
    op.create_table('v_dosen',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('nomor_induk', sa.String(length=20), nullable=True),
    sa.Column('nama', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('no_hp', sa.String(length=15), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('gelar_depan', sa.String(length=255), nullable=True),
    sa.Column('gelar_belakang', sa.String(length=255), nullable=True),
    sa.Column('nama_lengkap', sa.String(length=255), nullable=True),
    sa.Column('jabatan', sa.String(length=100), nullable=True),
    sa.Column('fakultas_id', sa.Integer(), nullable=True),
    sa.Column('nama_fakultas', sa.String(length=100), nullable=True),
    sa.Column('ttd_path', sa.String(length=255), nullable=True),
    sa.Column('signature_upload_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('v_mahasiswa',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('nomor_induk', sa.String(length=20), nullable=True),
    sa.Column('nama', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('no_hp', sa.String(length=15), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('semester', sa.Integer(), nullable=True),
    sa.Column('fakultas_id', sa.Integer(), nullable=True),
    sa.Column('nama_fakultas', sa.String(length=100), nullable=True),
    sa.Column('program_studi_id', sa.Integer(), nullable=True),
    sa.Column('nama_prodi', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('dosen',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('fakultas_id', sa.Integer(), nullable=True),
    sa.Column('gelar_depan', sa.String(length=255), nullable=True),
    sa.Column('gelar_belakang', sa.String(length=255), nullable=True),
    sa.Column('jabatan', sa.String(length=100), nullable=True),
    sa.Column('ttd_path', sa.String(length=255), nullable=True),
    sa.Column('signature_upload_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['fakultas_id'], ['fakultas.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('program_studi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fakultas_id', sa.Integer(), nullable=False),
    sa.Column('nama_prodi', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['fakultas_id'], ['fakultas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mahasiswa',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('fakultas_id', sa.Integer(), nullable=False),
    sa.Column('program_studi_id', sa.Integer(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fakultas_id'], ['fakultas.id'], ),
    sa.ForeignKeyConstraint(['program_studi_id'], ['program_studi.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('permohonan',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('id_jenis_permohonan', sa.Integer(), nullable=True),
    sa.Column('id_mahasiswa', sa.String(length=36), nullable=True),
    sa.Column('id_dosen', sa.String(length=36), nullable=True),
    sa.Column('judul', sa.String(length=255), nullable=False),
    sa.Column('deskripsi', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(length=255), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_signed_path', sa.String(length=255), nullable=True),
    sa.Column('komentar', sa.Text(), nullable=True),
    sa.Column('komentar_penolakan', sa.Text(), nullable=True),
    sa.Column('qr_code_data', sa.Text(), nullable=True),
    sa.Column('qr_code_path', sa.String(length=255), nullable=True),
    sa.Column('status_permohonan', sa.Enum('pending', 'disetujui', 'ditolak', 'ditandatangani', 'selesai', name='status_permohonan_enum'), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('signed_at', sa.DateTime(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_dosen'], ['dosen.user_id'], ),
    sa.ForeignKeyConstraint(['id_jenis_permohonan'], ['jenis_permohonan.id'], ),
    sa.ForeignKeyConstraint(['id_mahasiswa'], ['mahasiswa.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('permohonan_id', sa.String(length=36), nullable=True),
    sa.Column('id_jenis_permohonan', sa.Integer(), nullable=True),
    sa.Column('id_mahasiswa', sa.String(length=36), nullable=True),
    sa.Column('id_dosen', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('signature_hash', sa.String(length=255), nullable=True),
    sa.Column('qr_code_path', sa.String(length=255), nullable=True),
    sa.Column('signed_at', sa.DateTime(), nullable=True),
    sa.Column('komentar_permohonan', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_dosen'], ['dosen.user_id'], ),
    sa.ForeignKeyConstraint(['id_jenis_permohonan'], ['jenis_permohonan.id'], ),
    sa.ForeignKeyConstraint(['id_mahasiswa'], ['mahasiswa.user_id'], ),
    sa.ForeignKeyConstraint(['permohonan_id'], ['permohonan.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('permohonan_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['permohonan_id'], ['permohonan.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications')
    op.drop_table('history')
    op.drop_table('permohonan')
    op.drop_table('mahasiswa')
    op.drop_table('program_studi')
    op.drop_table('dosen')
    op.drop_table('v_mahasiswa')
    op.drop_table('v_dosen')
    op.drop_table('users')
    op.drop_table('jenis_permohonan')
    op.drop_table('fakultas')
    # ### end Alembic commands ###
